version: '3'

services:
  yt-dlp-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yt-dlp-api
    ports:
      - "3000:3000"
    volumes:
      - ./downloads:/downloads
    environment:
      - PORT=3000
      - DOWNLOADS_DIR=/downloads
      - NODE_ENV=production
    restart: unless-stopped 